import mirrorkey from 'mirrorkey';

export default mirrorkey([
    'GET_ALL_STUDENTS_REQUEST',
    'GET_ALL_STUDENTS_SUCCESS',
    'GET_ALL_STUDENTS_FAIL',
    'GET_STUDENT_REQUEST',
    'GET_STUDENT_SUCCESS',
    'GET_STUDENT_FAIL',
    'GET_COURSE_REQUEST',
    'GET_COURSE_SUCCESS',
    'GET_COURSE_FAIL',
    'GET_STUDENT_REPORT_REQUEST',
    'GET_STUDENT_REPORT_SUCCESS',
    'GET_STUDENT_REPORT_FAIL',
    'SAAS_UPLOAD_REQUEST_FAIL',
    'SAAS_UPLOAD_REQUEST_SUCCESS',
    'SAAS_UPLOAD_REQUEST',
    'UPDATE_REPORT_REQUEST',
    'UPDATE_REPORT_SUCCESS',
    'UPDATE_REPORT_FAIL',
    'SAAS_CONTACT_REQUEST',
    'SAAS_CONTACT_REQUEST_FAIL',
    'SAAS_CONTACT_REQUEST_SUCCESS'
]);